# Generated by Django 5.0.1 on 2024-01-22 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_product_products'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='vendors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
    ]
