# Generated by Django 4.2.9 on 2024-02-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_cartorderitems_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='invoice_No',
            field=models.CharField(default='No2304', max_length=200),
        ),
    ]
