# Generated by Django 5.0.1 on 2024-01-22 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_products_vendors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product',
            new_name='products',
        ),
    ]
