# Generated by Django 5.0.1 on 2024-01-22 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_product_productimage_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='products',
            new_name='product_names',
        ),
    ]
