# Generated by Django 5.0.1 on 2024-01-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_products_expiration_products_stock_products_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='mfd',
            field=models.DateTimeField(blank=True, default='2007-03-22 04:30', null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2007-03-22 04:30'),
            preserve_default=False,
        ),
    ]
