# Generated by Django 5.0.1 on 2024-01-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_products_expiration_remove_products_mfd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='exp',
            field=models.CharField(blank=True, default='200 days', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='manifec',
            field=models.DateTimeField(blank=True, default='2007-03-22 04:30', null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='stock_in',
            field=models.CharField(blank=True, default='10', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='type',
            field=models.CharField(blank=True, default='best selling', max_length=200, null=True),
        ),
    ]
