# Generated by Django 5.0.1 on 2024-01-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_products_exp_products_manifec_products_stock_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='exp',
            new_name='expiration',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='type',
            new_name='product_type',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='stock_in',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='products',
            name='manifec',
        ),
        migrations.AddField(
            model_name='products',
            name='mfd',
            field=models.DateTimeField(blank=True, default='2007-03-22 04:30', null=True),
        ),
    ]
