# Generated by Django 5.0.1 on 2024-01-25 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_products_mfd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='stock',
            new_name='my_stock',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='mfd',
            new_name='production_date',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_type',
            new_name='productkind',
        ),
    ]
