# Generated by Django 5.0.1 on 2024-01-25 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_rename_stock_products_my_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='production_date',
        ),
    ]
