# Generated by Django 5.0.1 on 2024-01-26 23:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_products_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sommary_product_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=100, null=True),
        ),
    ]
