# Generated by Django 5.0.1 on 2024-01-27 00:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_products_sommary_product_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sommary_product_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
